import ico_search from './search.png';
import ico_lm_search from './search_B.png';
import ico_bell from './bell.png';
import ico_lm_bell from './bell_B.png';
import ico_fb from './fb.png';
import ico_reload from './reload.png';
import ico_lm_reload from './reload_B.png';
import ico_X from './x.png';
import ico_sdefect from './s_defect.png';